name: 'Upload to OpenRepos.net'
description: 'Upload RPM packages to OpenRepos.net using Playwright automation'
branding:
  icon: package
  color: green
inputs:
  login:
    description: 'Username or e-mail of OpenRepos.net account'
    required: true
  password:
    description: 'Corresponding Password'
    required: true
  appName:
    description: 'Application name'
    required: true
  rpms:
    description: 'RPM file names delimited by new lines'
    required: true
  dry_run:
    description: 'Make a dry run: Login and upload but do not save.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OPENREPOS_USERNAME: ${{ inputs.login }}
    OPENREPOS_PASSWORD: ${{ inputs.password }}
    OPENREPOS_APPNAME: ${{ inputs.appName }}
  args:
    - "--rpms"
    - ${{ inputs.dry_run && '--dry-run' }}
