#!/usr/bin/env python3

import subprocess
import sys
from itertools import accumulate
from typing import Iterator


def prefix_sublists(version: list[str]) -> Iterator[str]:
    return accumulate(version, lambda *x: ".".join(x))


def run(args: list[str]):
    print(f"> {' '.join(args)}")
    subprocess.run(args, check=True)

def main():
    version = sys.argv[1]
    v = version.split(".")

    to_push: list[str] = []
    for v_prefix in prefix_sublists(v):
        prefix_version = '.'.join(v_prefix)
        run(["git", "tag", "-a", f"v{prefix_version}", "-m", f"Release {version}", "--force"])
        to_push.append(f"refs/tags/v{prefix_version}")
    
    run(["git", "push", "origin", "--force"] + to_push)


if __name__ == '__main__':
    main()
